export interface MusicOption {
  id: string
  label: string
  url: string | null
}

export const MUSIC_OPTIONS: MusicOption[] = [
  { id: "upbeat", label: "Upbeat", url: "/audio/music-upbeat.mp3" },
  { id: "calm", label: "Calm", url: "/audio/music-calm.mp3" },
  { id: "corporate", label: "Corporate", url: "/audio/music-corporate.mp3" },
  { id: "none", label: "No music", url: null },
]

// Keyword-matched, not a model call — MUSIC_OPTIONS only has 4 fixed
// entries, and the free-text mood descriptions this maps from (e.g.
// "Upbeat, futuristic electronic music") are generated by the same prompt
// style every time, so a handful of keywords per bucket covers the
// realistic range without the latency/cost of an extra classification call.
const NONE_PATTERN = /\b(no music|no audio|silence|silent|none)\b/
const UPBEAT_PATTERN = /\b(upbeat|energetic|energizing|exciting|fun|hype|dynamic|lively|peppy|uptempo)\b/
const CALM_PATTERN = /\b(calm|soothing|relaxed|chill|mellow|gentle|soft|peaceful|serene|ambient)\b/
const CORPORATE_PATTERN = /\b(professional|corporate|business|formal|serious)\b/

/** Maps a free-text audio mood description to a MUSIC_OPTIONS id, defaulting
 * to "upbeat" (the same fallback reel-scripts/[scriptId]/video/route.ts uses
 * for an unrecognized/omitted musicTrackId) when nothing matches. */
export function resolveMusicTrackId(moodText: string | null | undefined): string {
  const text = (moodText ?? "").toLowerCase()
  if (NONE_PATTERN.test(text)) return "none"
  if (UPBEAT_PATTERN.test(text)) return "upbeat"
  if (CALM_PATTERN.test(text)) return "calm"
  if (CORPORATE_PATTERN.test(text)) return "corporate"
  return "upbeat"
}
