-- 011_stories_table.sql
-- Story sequences generated by StorySequence.tsx had no real persistence
-- destination before this migration — the component was POSTing to
-- /api/v1/brands/[brandId]/reel-scripts, which has no POST handler, so the
-- save silently no-opped every time. This adds a proper home for them,
-- mirroring the reel_scripts/carousels table shape.

CREATE TABLE public.stories (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  brand_id    UUID NOT NULL REFERENCES public.brands(id) ON DELETE CASCADE,
  product_id  UUID REFERENCES public.products(id) ON DELETE SET NULL,
  topic       TEXT,
  stories     JSONB NOT NULL DEFAULT '[]',
  is_saved    BOOLEAN DEFAULT true,
  user_rating INTEGER CHECK (user_rating BETWEEN 1 AND 5),
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.stories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users_own_stories" ON public.stories FOR ALL USING (
  brand_id IN (SELECT id FROM public.brands WHERE user_id = auth.uid())
);
