/**
 * This file will be auto-generated by running:
 * npx supabase gen types typescript --project-id YOUR_PROJECT_ID > types/database.ts
 *
 * The types below are a manual scaffold until you run that command.
 * Replace this entire file after running the generator.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          full_name: string | null
          avatar_url: string | null
          plan: "free" | "starter" | "pro" | "agency"
          stripe_customer_id: string | null
          generation_count: number
          generation_count_reset_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          avatar_url?: string | null
          plan?: "free" | "starter" | "pro" | "agency"
          stripe_customer_id?: string | null
          generation_count?: number
          generation_count_reset_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          email?: string
          full_name?: string | null
          avatar_url?: string | null
          plan?: "free" | "starter" | "pro" | "agency"
          stripe_customer_id?: string | null
          generation_count?: number
          generation_count_reset_at?: string | null
          updated_at?: string
        }
      }
      brands: {
        Row: {
          id: string
          user_id: string
          name: string
          description: string | null
          niche: string | null
          target_audience: string | null
          tone_of_voice: string | null
          brand_values: string[]
          competitors: string[]
          color_palette: Json
          logo_url: string | null
          website_url: string | null
          instagram_handle: string | null
          ai_persona: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          description?: string | null
          niche?: string | null
          target_audience?: string | null
          tone_of_voice?: string | null
          brand_values?: string[]
          competitors?: string[]
          color_palette?: Json
          logo_url?: string | null
          website_url?: string | null
          instagram_handle?: string | null
          ai_persona?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          name?: string
          description?: string | null
          niche?: string | null
          target_audience?: string | null
          tone_of_voice?: string | null
          brand_values?: string[]
          competitors?: string[]
          color_palette?: Json
          logo_url?: string | null
          website_url?: string | null
          instagram_handle?: string | null
          ai_persona?: string | null
          is_active?: boolean
          updated_at?: string
        }
      }
      products: {
        Row: {
          id: string
          brand_id: string
          name: string
          description: string | null
          price: number | null
          currency: string
          category: string | null
          key_benefits: string[]
          ingredients: string | null
          target_customer: string | null
          image_urls: string[]
          shopify_product_id: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          brand_id: string
          name: string
          description?: string | null
          price?: number | null
          currency?: string
          category?: string | null
          key_benefits?: string[]
          ingredients?: string | null
          target_customer?: string | null
          image_urls?: string[]
          shopify_product_id?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          name?: string
          description?: string | null
          price?: number | null
          currency?: string
          category?: string | null
          key_benefits?: string[]
          ingredients?: string | null
          target_customer?: string | null
          image_urls?: string[]
          shopify_product_id?: string | null
          is_active?: boolean
          updated_at?: string
        }
      }
      content_projects: {
        Row: {
          id: string
          brand_id: string
          product_id: string | null
          title: string
          status: "draft" | "review" | "approved" | "scheduled" | "published"
          platform: "instagram" | "facebook" | "tiktok" | "youtube" | "linkedin" | "twitter" | null
          content_type: "reel" | "post" | "story" | "carousel" | "thread" | null
          selected_hook: string | null
          selected_caption: string | null
          notes: string | null
          media_urls: string[]
          scheduled_at: string | null
          published_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          brand_id: string
          product_id?: string | null
          title: string
          status?: "draft" | "review" | "approved" | "scheduled" | "published"
          platform?: "instagram" | "facebook" | "tiktok" | "youtube" | "linkedin" | "twitter" | null
          content_type?: "reel" | "post" | "story" | "carousel" | "thread" | null
          selected_hook?: string | null
          selected_caption?: string | null
          notes?: string | null
          media_urls?: string[]
          scheduled_at?: string | null
          published_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          title?: string
          status?: "draft" | "review" | "approved" | "scheduled" | "published"
          platform?: "instagram" | "facebook" | "tiktok" | "youtube" | "linkedin" | "twitter" | null
          content_type?: "reel" | "post" | "story" | "carousel" | "thread" | null
          selected_hook?: string | null
          selected_caption?: string | null
          notes?: string | null
          media_urls?: string[]
          scheduled_at?: string | null
          published_at?: string | null
          updated_at?: string
        }
      }
      hooks: {
        Row: {
          id: string
          content_project_id: string | null
          brand_id: string
          product_id: string | null
          hook_text: string
          hook_type: "question" | "bold_statement" | "story" | "statistic" | "controversial" | "how_to" | null
          generation_prompt: string | null
          model_used: string
          is_saved: boolean
          is_used: boolean
          user_rating: number | null
          performance_score: number | null
          created_at: string
        }
        Insert: {
          id?: string
          content_project_id?: string | null
          brand_id: string
          product_id?: string | null
          hook_text: string
          hook_type?: "question" | "bold_statement" | "story" | "statistic" | "controversial" | "how_to" | null
          generation_prompt?: string | null
          model_used?: string
          is_saved?: boolean
          is_used?: boolean
          user_rating?: number | null
          performance_score?: number | null
          created_at?: string
        }
        Update: {
          hook_text?: string
          hook_type?: "question" | "bold_statement" | "story" | "statistic" | "controversial" | "how_to" | null
          is_saved?: boolean
          is_used?: boolean
          user_rating?: number | null
          performance_score?: number | null
        }
      }
      captions: {
        Row: {
          id: string
          content_project_id: string | null
          hook_id: string | null
          brand_id: string
          caption_text: string
          hashtags: string[]
          cta: string | null
          character_count: number | null
          platform: string | null
          generation_prompt: string | null
          model_used: string
          tone_used: string | null
          is_saved: boolean
          user_rating: number | null
          performance_score: number | null
          created_at: string
        }
        Insert: {
          id?: string
          content_project_id?: string | null
          hook_id?: string | null
          brand_id: string
          caption_text: string
          hashtags?: string[]
          cta?: string | null
          character_count?: number | null
          platform?: string | null
          generation_prompt?: string | null
          model_used?: string
          tone_used?: string | null
          is_saved?: boolean
          user_rating?: number | null
          performance_score?: number | null
          created_at?: string
        }
        Update: {
          caption_text?: string
          hashtags?: string[]
          cta?: string | null
          is_saved?: boolean
          user_rating?: number | null
          performance_score?: number | null
        }
      }
      calendar_entries: {
        Row: {
          id: string
          brand_id: string
          content_project_id: string | null
          title: string
          scheduled_date: string
          scheduled_time: string | null
          platform: string | null
          content_type: string | null
          status: "planned" | "content_ready" | "scheduled" | "published" | "missed"
          color: string
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          brand_id: string
          content_project_id?: string | null
          title: string
          scheduled_date: string
          scheduled_time?: string | null
          platform?: string | null
          content_type?: string | null
          status?: "planned" | "content_ready" | "scheduled" | "published" | "missed"
          color?: string
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          title?: string
          scheduled_date?: string
          scheduled_time?: string | null
          platform?: string | null
          content_type?: string | null
          status?: "planned" | "content_ready" | "scheduled" | "published" | "missed"
          color?: string
          notes?: string | null
          updated_at?: string
        }
      }
      ai_generation_logs: {
        Row: {
          id: string
          user_id: string
          brand_id: string | null
          feature: string
          model: string
          prompt_tokens: number | null
          completion_tokens: number | null
          total_tokens: number | null
          cost_usd: number | null
          latency_ms: number | null
          success: boolean
          error_message: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          brand_id?: string | null
          feature: string
          model: string
          prompt_tokens?: number | null
          completion_tokens?: number | null
          total_tokens?: number | null
          cost_usd?: number | null
          latency_ms?: number | null
          success?: boolean
          error_message?: string | null
          created_at?: string
        }
        Update: never
      }
      generated_images: {
        Row: {
          id: string
          content_project_id: string | null
          brand_id: string
          product_id: string | null
          prompt: string
          style: string | null
          aspect_ratio: "1:1" | "4:5" | "9:16" | "16:9"
          storage_path: string
          public_url: string
          model_used: string
          is_saved: boolean
          created_at: string
        }
        Insert: {
          id?: string
          content_project_id?: string | null
          brand_id: string
          product_id?: string | null
          prompt: string
          style?: string | null
          aspect_ratio?: "1:1" | "4:5" | "9:16" | "16:9"
          storage_path: string
          public_url: string
          model_used?: string
          is_saved?: boolean
          created_at?: string
        }
        Update: {
          is_saved?: boolean
        }
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}

// Convenience row types
export type UserRow = Database["public"]["Tables"]["users"]["Row"]
export type BrandRow = Database["public"]["Tables"]["brands"]["Row"]
export type ProductRow = Database["public"]["Tables"]["products"]["Row"]
export type ContentProjectRow = Database["public"]["Tables"]["content_projects"]["Row"]
export type HookRow = Database["public"]["Tables"]["hooks"]["Row"]
export type CaptionRow = Database["public"]["Tables"]["captions"]["Row"]
export type CalendarEntryRow = Database["public"]["Tables"]["calendar_entries"]["Row"]
export type AIGenerationLogRow = Database["public"]["Tables"]["ai_generation_logs"]["Row"]
export type GeneratedImageRow = Database["public"]["Tables"]["generated_images"]["Row"]

// Insert types
export type UserInsert = Database["public"]["Tables"]["users"]["Insert"]
export type BrandInsert = Database["public"]["Tables"]["brands"]["Insert"]
export type ProductInsert = Database["public"]["Tables"]["products"]["Insert"]
export type ContentProjectInsert = Database["public"]["Tables"]["content_projects"]["Insert"]
export type HookInsert = Database["public"]["Tables"]["hooks"]["Insert"]
export type CaptionInsert = Database["public"]["Tables"]["captions"]["Insert"]
export type CalendarEntryInsert = Database["public"]["Tables"]["calendar_entries"]["Insert"]
export type AIGenerationLogInsert = Database["public"]["Tables"]["ai_generation_logs"]["Insert"]
export type GeneratedImageInsert = Database["public"]["Tables"]["generated_images"]["Insert"]
