/**
 * This file will be auto-generated by running:
 * npx supabase gen types typescript --project-id YOUR_PROJECT_ID > types/database.ts
 *
 * The types below are a manual scaffold until you run that command.
 * Replace this entire file after running the generator.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          full_name: string | null
          avatar_url: string | null
          plan: "free" | "starter" | "pro" | "agency"
          stripe_customer_id: string | null
          generation_count: number
          generation_count_reset_at: string | null
          onboarding_completed: boolean | null
          onboarding_type: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          avatar_url?: string | null
          plan?: "free" | "starter" | "pro" | "agency"
          stripe_customer_id?: string | null
          generation_count?: number
          generation_count_reset_at?: string | null
          onboarding_completed?: boolean | null
          onboarding_type?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          email?: string
          full_name?: string | null
          avatar_url?: string | null
          plan?: "free" | "starter" | "pro" | "agency"
          stripe_customer_id?: string | null
          generation_count?: number
          generation_count_reset_at?: string | null
          onboarding_completed?: boolean | null
          onboarding_type?: string | null
          updated_at?: string
        }
      }
      brands: {
        Row: {
          id: string
          user_id: string
          name: string
          description: string | null
          niche: string | null
          target_audience: string | null
          tone_of_voice: string | null
          brand_values: string[]
          competitors: string[]
          color_palette: Json
          logo_url: string | null
          website_url: string | null
          instagram_handle: string | null
          ai_persona: string | null
          primary_color: string | null
          cta_phrase: string | null
          brand_personality: string | null
          content_pillars: string[]
          target_emotion: string | null
          vibe: string | null
          onboarding_type: string | null
          posting_frequency: string | null
          target_platforms: string[] | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          description?: string | null
          niche?: string | null
          target_audience?: string | null
          tone_of_voice?: string | null
          brand_values?: string[]
          competitors?: string[]
          color_palette?: Json
          logo_url?: string | null
          website_url?: string | null
          instagram_handle?: string | null
          ai_persona?: string | null
          primary_color?: string | null
          cta_phrase?: string | null
          brand_personality?: string | null
          content_pillars?: string[]
          target_emotion?: string | null
          vibe?: string | null
          onboarding_type?: string | null
          posting_frequency?: string | null
          target_platforms?: string[] | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          name?: string
          description?: string | null
          niche?: string | null
          target_audience?: string | null
          tone_of_voice?: string | null
          brand_values?: string[]
          competitors?: string[]
          color_palette?: Json
          logo_url?: string | null
          website_url?: string | null
          instagram_handle?: string | null
          ai_persona?: string | null
          primary_color?: string | null
          cta_phrase?: string | null
          brand_personality?: string | null
          content_pillars?: string[]
          target_emotion?: string | null
          vibe?: string | null
          onboarding_type?: string | null
          posting_frequency?: string | null
          target_platforms?: string[] | null
          is_active?: boolean
          updated_at?: string
        }
      }
      brand_images: {
        Row: {
          id: string
          brand_id: string
          url: string
          alt: string | null
          type: string
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          brand_id: string
          url: string
          alt?: string | null
          type?: string
          is_active?: boolean
          created_at?: string
        }
        Update: {
          url?: string
          alt?: string | null
          type?: string
          is_active?: boolean
        }
      }
      products: {
        Row: {
          id: string
          brand_id: string
          name: string
          description: string | null
          price: number | null
          currency: string
          category: string | null
          key_benefits: string[]
          ingredients: string | null
          target_customer: string | null
          image_urls: string[]
          shopify_product_id: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          brand_id: string
          name: string
          description?: string | null
          price?: number | null
          currency?: string
          category?: string | null
          key_benefits?: string[]
          ingredients?: string | null
          target_customer?: string | null
          image_urls?: string[]
          shopify_product_id?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          name?: string
          description?: string | null
          price?: number | null
          currency?: string
          category?: string | null
          key_benefits?: string[]
          ingredients?: string | null
          target_customer?: string | null
          image_urls?: string[]
          shopify_product_id?: string | null
          is_active?: boolean
          updated_at?: string
        }
      }
      content_projects: {
        Row: {
          id: string
          brand_id: string
          product_id: string | null
          title: string
          status: "draft" | "review" | "approved" | "scheduled" | "published"
          platform: "instagram" | "facebook" | "tiktok" | "youtube" | "linkedin" | "twitter" | null
          content_type: "reel" | "post" | "story" | "carousel" | "thread" | null
          selected_hook: string | null
          selected_caption: string | null
          notes: string | null
          media_urls: string[]
          scheduled_at: string | null
          published_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          brand_id: string
          product_id?: string | null
          title: string
          status?: "draft" | "review" | "approved" | "scheduled" | "published"
          platform?: "instagram" | "facebook" | "tiktok" | "youtube" | "linkedin" | "twitter" | null
          content_type?: "reel" | "post" | "story" | "carousel" | "thread" | null
          selected_hook?: string | null
          selected_caption?: string | null
          notes?: string | null
          media_urls?: string[]
          scheduled_at?: string | null
          published_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          title?: string
          status?: "draft" | "review" | "approved" | "scheduled" | "published"
          platform?: "instagram" | "facebook" | "tiktok" | "youtube" | "linkedin" | "twitter" | null
          content_type?: "reel" | "post" | "story" | "carousel" | "thread" | null
          selected_hook?: string | null
          selected_caption?: string | null
          notes?: string | null
          media_urls?: string[]
          scheduled_at?: string | null
          published_at?: string | null
          updated_at?: string
        }
      }
      hooks: {
        Row: {
          id: string
          content_project_id: string | null
          brand_id: string
          product_id: string | null
          hook_text: string
          hook_type: "question" | "bold_statement" | "story" | "statistic" | "controversial" | "how_to" | null
          generation_prompt: string | null
          model_used: string
          is_saved: boolean
          is_used: boolean
          user_rating: number | null
          performance_score: number | null
          created_at: string
        }
        Insert: {
          id?: string
          content_project_id?: string | null
          brand_id: string
          product_id?: string | null
          hook_text: string
          hook_type?: "question" | "bold_statement" | "story" | "statistic" | "controversial" | "how_to" | null
          generation_prompt?: string | null
          model_used?: string
          is_saved?: boolean
          is_used?: boolean
          user_rating?: number | null
          performance_score?: number | null
          created_at?: string
        }
        Update: {
          hook_text?: string
          hook_type?: "question" | "bold_statement" | "story" | "statistic" | "controversial" | "how_to" | null
          is_saved?: boolean
          is_used?: boolean
          user_rating?: number | null
          performance_score?: number | null
        }
      }
      captions: {
        Row: {
          id: string
          content_project_id: string | null
          hook_id: string | null
          brand_id: string
          caption_text: string
          hashtags: string[]
          cta: string | null
          character_count: number | null
          platform: string | null
          generation_prompt: string | null
          model_used: string
          tone_used: string | null
          is_saved: boolean
          user_rating: number | null
          performance_score: number | null
          created_at: string
        }
        Insert: {
          id?: string
          content_project_id?: string | null
          hook_id?: string | null
          brand_id: string
          caption_text: string
          hashtags?: string[]
          cta?: string | null
          character_count?: number | null
          platform?: string | null
          generation_prompt?: string | null
          model_used?: string
          tone_used?: string | null
          is_saved?: boolean
          user_rating?: number | null
          performance_score?: number | null
          created_at?: string
        }
        Update: {
          caption_text?: string
          hashtags?: string[]
          cta?: string | null
          is_saved?: boolean
          user_rating?: number | null
          performance_score?: number | null
        }
      }
      calendar_entries: {
        Row: {
          id: string
          brand_id: string
          content_project_id: string | null
          title: string
          scheduled_date: string
          scheduled_time: string | null
          platform: string | null
          content_type: string | null
          status: "planned" | "content_ready" | "scheduled" | "published" | "missed"
          color: string
          notes: string | null
          hook_text: string | null
          caption_text: string | null
          hashtags: string[]
          visual_direction: string | null
          audio_suggestion: string | null
          content_type_detail: string | null
          hook_id: string | null
          caption_id: string | null
          is_ready: boolean
          platform_specific_data: Json
          publish_attempts: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          brand_id: string
          content_project_id?: string | null
          title: string
          scheduled_date: string
          scheduled_time?: string | null
          platform?: string | null
          content_type?: string | null
          status?: "planned" | "content_ready" | "scheduled" | "published" | "missed"
          color?: string
          notes?: string | null
          hook_text?: string | null
          caption_text?: string | null
          hashtags?: string[]
          visual_direction?: string | null
          audio_suggestion?: string | null
          content_type_detail?: string | null
          hook_id?: string | null
          caption_id?: string | null
          is_ready?: boolean
          platform_specific_data?: Json
          publish_attempts?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          title?: string
          scheduled_date?: string
          scheduled_time?: string | null
          platform?: string | null
          content_type?: string | null
          status?: "planned" | "content_ready" | "scheduled" | "published" | "missed"
          color?: string
          notes?: string | null
          hook_text?: string | null
          caption_text?: string | null
          hashtags?: string[]
          visual_direction?: string | null
          audio_suggestion?: string | null
          content_type_detail?: string | null
          hook_id?: string | null
          caption_id?: string | null
          is_ready?: boolean
          platform_specific_data?: Json
          publish_attempts?: number
          updated_at?: string
        }
      }
      influencers: {
        Row: {
          id: string
          brand_id: string
          platform: "instagram" | "tiktok" | "youtube"
          handle: string
          full_name: string | null
          bio: string | null
          follower_count: number | null
          following_count: number | null
          post_count: number | null
          avg_engagement_rate: number | null
          profile_url: string | null
          avatar_url: string | null
          niche: string | null
          location: string | null
          fit_score: number | null
          fit_reasoning: string | null
          raw_scraped_data: Record<string, unknown>
          status: "discovered" | "contacted" | "replied" | "negotiating" | "partnered" | "rejected" | "completed"
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          brand_id: string
          platform: "instagram" | "tiktok" | "youtube"
          handle: string
          full_name?: string | null
          bio?: string | null
          follower_count?: number | null
          following_count?: number | null
          post_count?: number | null
          avg_engagement_rate?: number | null
          profile_url?: string | null
          avatar_url?: string | null
          niche?: string | null
          location?: string | null
          fit_score?: number | null
          fit_reasoning?: string | null
          raw_scraped_data?: Record<string, unknown>
          status?: "discovered" | "contacted" | "replied" | "negotiating" | "partnered" | "rejected" | "completed"
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          handle?: string
          full_name?: string | null
          bio?: string | null
          follower_count?: number | null
          following_count?: number | null
          post_count?: number | null
          avg_engagement_rate?: number | null
          profile_url?: string | null
          avatar_url?: string | null
          niche?: string | null
          location?: string | null
          fit_score?: number | null
          fit_reasoning?: string | null
          raw_scraped_data?: Record<string, unknown>
          status?: "discovered" | "contacted" | "replied" | "negotiating" | "partnered" | "rejected" | "completed"
          notes?: string | null
          updated_at?: string
        }
      }
      influencer_partnerships: {
        Row: {
          id: string
          influencer_id: string
          brand_id: string
          campaign_name: string
          campaign_brief: string | null
          deliverables: string[]
          talking_points: string[]
          dos: string[]
          donts: string[]
          key_hashtags: string[]
          compensation_type: "paid" | "gifted" | "affiliate" | "collab" | null
          compensation_amount: number | null
          currency: string
          timeline_start: string | null
          timeline_end: string | null
          status: "draft" | "sent" | "active" | "completed" | "cancelled"
          actual_reach: number | null
          actual_engagement: number | null
          conversions: number | null
          roi_notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          influencer_id: string
          brand_id: string
          campaign_name: string
          campaign_brief?: string | null
          deliverables?: string[]
          talking_points?: string[]
          dos?: string[]
          donts?: string[]
          key_hashtags?: string[]
          compensation_type?: "paid" | "gifted" | "affiliate" | "collab" | null
          compensation_amount?: number | null
          currency?: string
          timeline_start?: string | null
          timeline_end?: string | null
          status?: "draft" | "sent" | "active" | "completed" | "cancelled"
          actual_reach?: number | null
          actual_engagement?: number | null
          conversions?: number | null
          roi_notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          campaign_name?: string
          campaign_brief?: string | null
          deliverables?: string[]
          talking_points?: string[]
          dos?: string[]
          donts?: string[]
          key_hashtags?: string[]
          compensation_type?: "paid" | "gifted" | "affiliate" | "collab" | null
          compensation_amount?: number | null
          currency?: string
          timeline_start?: string | null
          timeline_end?: string | null
          status?: "draft" | "sent" | "active" | "completed" | "cancelled"
          actual_reach?: number | null
          actual_engagement?: number | null
          conversions?: number | null
          roi_notes?: string | null
          updated_at?: string
        }
      }
      outreach_messages: {
        Row: {
          id: string
          influencer_id: string
          brand_id: string
          channel: "dm" | "email" | "whatsapp"
          subject: string | null
          message_text: string
          tone: string | null
          sent_at: string | null
          replied_at: string | null
          reply_text: string | null
          created_at: string
        }
        Insert: {
          id?: string
          influencer_id: string
          brand_id: string
          channel: "dm" | "email" | "whatsapp"
          subject?: string | null
          message_text: string
          tone?: string | null
          sent_at?: string | null
          replied_at?: string | null
          reply_text?: string | null
          created_at?: string
        }
        Update: {
          channel?: "dm" | "email" | "whatsapp"
          subject?: string | null
          message_text?: string
          tone?: string | null
          sent_at?: string | null
          replied_at?: string | null
          reply_text?: string | null
        }
      }
      ai_generation_logs: {
        Row: {
          id: string
          user_id: string
          brand_id: string | null
          feature: string
          model: string
          prompt_tokens: number | null
          completion_tokens: number | null
          total_tokens: number | null
          cost_usd: number | null
          latency_ms: number | null
          success: boolean
          error_message: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          brand_id?: string | null
          feature: string
          model: string
          prompt_tokens?: number | null
          completion_tokens?: number | null
          total_tokens?: number | null
          cost_usd?: number | null
          latency_ms?: number | null
          success?: boolean
          error_message?: string | null
          created_at?: string
        }
        Update: never
      }
      generated_images: {
        Row: {
          id: string
          content_project_id: string | null
          brand_id: string
          product_id: string | null
          prompt: string
          style: string | null
          aspect_ratio: "1:1" | "4:5" | "9:16" | "16:9"
          storage_path: string
          public_url: string
          model_used: string
          is_saved: boolean
          created_at: string
        }
        Insert: {
          id?: string
          content_project_id?: string | null
          brand_id: string
          product_id?: string | null
          prompt: string
          style?: string | null
          aspect_ratio?: "1:1" | "4:5" | "9:16" | "16:9"
          storage_path: string
          public_url: string
          model_used?: string
          is_saved?: boolean
          created_at?: string
        }
        Update: {
          is_saved?: boolean
        }
      }
      reel_scripts: {
        Row: {
          id: string
          brand_id: string
          product_id: string | null
          platform: string | null
          hook: string
          scenes: Json
          caption: string | null
          hashtags: string[]
          duration_seconds: number | null
          is_saved: boolean
          user_rating: number | null
          created_at: string
        }
        Insert: {
          id?: string
          brand_id: string
          product_id?: string | null
          platform?: string | null
          hook: string
          scenes?: Json
          caption?: string | null
          hashtags?: string[]
          duration_seconds?: number | null
          is_saved?: boolean
          user_rating?: number | null
          created_at?: string
        }
        Update: {
          is_saved?: boolean
          user_rating?: number | null
        }
      }
      carousels: {
        Row: {
          id: string
          brand_id: string
          product_id: string | null
          platform: string | null
          title: string | null
          slides: Json
          hashtags: string[]
          is_saved: boolean
          user_rating: number | null
          created_at: string
        }
        Insert: {
          id?: string
          brand_id: string
          product_id?: string | null
          platform?: string | null
          title?: string | null
          slides?: Json
          hashtags?: string[]
          is_saved?: boolean
          user_rating?: number | null
          created_at?: string
        }
        Update: {
          is_saved?: boolean
          user_rating?: number | null
        }
      }
      ad_copies: {
        Row: {
          id: string
          brand_id: string
          product_id: string | null
          platform: string | null
          headline: string
          primary_text: string
          description: string | null
          cta_button: string | null
          character_counts: Json
          is_saved: boolean
          user_rating: number | null
          created_at: string
        }
        Insert: {
          id?: string
          brand_id: string
          product_id?: string | null
          platform?: string | null
          headline: string
          primary_text: string
          description?: string | null
          cta_button?: string | null
          character_counts?: Json
          is_saved?: boolean
          user_rating?: number | null
          created_at?: string
        }
        Update: {
          is_saved?: boolean
          user_rating?: number | null
        }
      }
      email_sequences: {
        Row: {
          id: string
          brand_id: string
          product_id: string | null
          sequence_type: string | null
          emails: Json
          is_saved: boolean
          user_rating: number | null
          created_at: string
        }
        Insert: {
          id?: string
          brand_id: string
          product_id?: string | null
          sequence_type?: string | null
          emails?: Json
          is_saved?: boolean
          user_rating?: number | null
          created_at?: string
        }
        Update: {
          is_saved?: boolean
          user_rating?: number | null
        }
      }
      product_descriptions: {
        Row: {
          id: string
          brand_id: string
          product_id: string | null
          short_description: string | null
          long_description: string | null
          bullet_points: string[]
          meta_description: string | null
          is_saved: boolean
          user_rating: number | null
          created_at: string
        }
        Insert: {
          id?: string
          brand_id: string
          product_id?: string | null
          short_description?: string | null
          long_description?: string | null
          bullet_points?: string[]
          meta_description?: string | null
          is_saved?: boolean
          user_rating?: number | null
          created_at?: string
        }
        Update: {
          is_saved?: boolean
          user_rating?: number | null
        }
      }
      social_connections: {
        Row: {
          id: string
          brand_id: string
          platform: "instagram" | "threads" | "pinterest" | "linkedin" | "youtube"
          ig_business_account_id: string | null
          ig_username: string | null
          facebook_page_id: string
          threads_user_id: string | null
          threads_username: string | null
          pinterest_user_id: string | null
          pinterest_username: string | null
          pinterest_board_id: string | null
          pinterest_board_name: string | null
          zernio_profile_id: string | null
          zernio_account_id: string | null
          linkedin_username: string | null
          youtube_channel_name: string | null
          access_token: string
          refresh_token: string | null
          token_expires_at: string
          connected_at: string
          last_refreshed_at: string
          is_active: boolean
        }
        Insert: {
          id?: string
          brand_id: string
          platform: "instagram" | "threads" | "pinterest" | "linkedin" | "youtube"
          ig_business_account_id?: string | null
          ig_username?: string | null
          facebook_page_id?: string | null
          threads_user_id?: string | null
          threads_username?: string | null
          pinterest_user_id?: string | null
          pinterest_username?: string | null
          pinterest_board_id?: string | null
          pinterest_board_name?: string | null
          zernio_profile_id?: string | null
          zernio_account_id?: string | null
          linkedin_username?: string | null
          youtube_channel_name?: string | null
          access_token: string | null
          refresh_token?: string | null
          token_expires_at: string | null
          connected_at?: string
          last_refreshed_at?: string
          is_active?: boolean
        }
        Update: {
          ig_business_account_id?: string | null
          ig_username?: string | null
          facebook_page_id?: string
          threads_user_id?: string | null
          threads_username?: string | null
          pinterest_user_id?: string | null
          pinterest_username?: string | null
          pinterest_board_id?: string | null
          pinterest_board_name?: string | null
          zernio_profile_id?: string | null
          zernio_account_id?: string | null
          linkedin_username?: string | null
          access_token?: string | null
          refresh_token?: string | null
          token_expires_at?: string | null
          last_refreshed_at?: string
          is_active?: boolean
        }
      }
      reel_video_jobs: {
        Row: {
          id: string
          brand_id: string
          reel_script_id: string
          status: "pending" | "generating_images" | "generating_voiceover" | "assets_ready" | "rendering" | "completed" | "failed"
          progress_message: string | null
          scene_assets: Json
          music_url: string | null
          video_url: string | null
          error_message: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          brand_id: string
          reel_script_id: string
          status?: "pending" | "generating_images" | "generating_voiceover" | "assets_ready" | "rendering" | "completed" | "failed"
          progress_message?: string | null
          scene_assets?: Json
          music_url?: string | null
          video_url?: string | null
          error_message?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          status?: "pending" | "generating_images" | "generating_voiceover" | "assets_ready" | "rendering" | "completed" | "failed"
          progress_message?: string | null
          scene_assets?: Json
          music_url?: string | null
          video_url?: string | null
          error_message?: string | null
          updated_at?: string
        }
      }
      stories: {
        Row: {
          id: string
          brand_id: string
          product_id: string | null
          topic: string | null
          stories: Json
          is_saved: boolean
          user_rating: number | null
          created_at: string
        }
        Insert: {
          id?: string
          brand_id: string
          product_id?: string | null
          topic?: string | null
          stories?: Json
          is_saved?: boolean
          user_rating?: number | null
          created_at?: string
        }
        Update: {
          is_saved?: boolean
          user_rating?: number | null
        }
      }
      memes: {
        Row: {
          id: string
          brand_id: string
          idea: string
          image_url: string
          top_text: string | null
          bottom_text: string | null
          caption: string | null
          hashtags: string[]
          is_saved: boolean
          user_rating: number | null
          created_at: string
        }
        Insert: {
          id?: string
          brand_id: string
          idea: string
          image_url: string
          top_text?: string | null
          bottom_text?: string | null
          caption?: string | null
          hashtags?: string[]
          is_saved?: boolean
          user_rating?: number | null
          created_at?: string
        }
        Update: {
          is_saved?: boolean
          user_rating?: number | null
        }
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}

// Convenience row types
export type UserRow = Database["public"]["Tables"]["users"]["Row"]
export type BrandRow = Database["public"]["Tables"]["brands"]["Row"]
export type ProductRow = Database["public"]["Tables"]["products"]["Row"]
export type ContentProjectRow = Database["public"]["Tables"]["content_projects"]["Row"]
export type HookRow = Database["public"]["Tables"]["hooks"]["Row"]
export type CaptionRow = Database["public"]["Tables"]["captions"]["Row"]
export type CalendarEntryRow = Database["public"]["Tables"]["calendar_entries"]["Row"]
export type AIGenerationLogRow = Database["public"]["Tables"]["ai_generation_logs"]["Row"]
export type GeneratedImageRow = Database["public"]["Tables"]["generated_images"]["Row"]
export type InfluencerRow = Database["public"]["Tables"]["influencers"]["Row"]
export type InfluencerPartnershipRow = Database["public"]["Tables"]["influencer_partnerships"]["Row"]
export type OutreachMessageRow = Database["public"]["Tables"]["outreach_messages"]["Row"]
export type ReelScriptRow = Database["public"]["Tables"]["reel_scripts"]["Row"]
export type CarouselRow = Database["public"]["Tables"]["carousels"]["Row"]
export type AdCopyRow = Database["public"]["Tables"]["ad_copies"]["Row"]
export type EmailSequenceRow = Database["public"]["Tables"]["email_sequences"]["Row"]
export type ProductDescriptionRow = Database["public"]["Tables"]["product_descriptions"]["Row"]
export type SocialConnectionRow = Database["public"]["Tables"]["social_connections"]["Row"]
export type ReelVideoJobRow = Database["public"]["Tables"]["reel_video_jobs"]["Row"]
export type StoryRow = Database["public"]["Tables"]["stories"]["Row"]
export type MemeRow = Database["public"]["Tables"]["memes"]["Row"]

// Insert types
export type UserInsert = Database["public"]["Tables"]["users"]["Insert"]
export type BrandInsert = Database["public"]["Tables"]["brands"]["Insert"]
export type ProductInsert = Database["public"]["Tables"]["products"]["Insert"]
export type ContentProjectInsert = Database["public"]["Tables"]["content_projects"]["Insert"]
export type HookInsert = Database["public"]["Tables"]["hooks"]["Insert"]
export type CaptionInsert = Database["public"]["Tables"]["captions"]["Insert"]
export type CalendarEntryInsert = Database["public"]["Tables"]["calendar_entries"]["Insert"]
export type AIGenerationLogInsert = Database["public"]["Tables"]["ai_generation_logs"]["Insert"]
export type GeneratedImageInsert = Database["public"]["Tables"]["generated_images"]["Insert"]
export type InfluencerInsert = Database["public"]["Tables"]["influencers"]["Insert"]
export type InfluencerPartnershipInsert = Database["public"]["Tables"]["influencer_partnerships"]["Insert"]
export type OutreachMessageInsert = Database["public"]["Tables"]["outreach_messages"]["Insert"]
export type ReelScriptInsert = Database["public"]["Tables"]["reel_scripts"]["Insert"]
export type CarouselInsert = Database["public"]["Tables"]["carousels"]["Insert"]
export type AdCopyInsert = Database["public"]["Tables"]["ad_copies"]["Insert"]
export type EmailSequenceInsert = Database["public"]["Tables"]["email_sequences"]["Insert"]
export type ProductDescriptionInsert = Database["public"]["Tables"]["product_descriptions"]["Insert"]
export type SocialConnectionInsert = Database["public"]["Tables"]["social_connections"]["Insert"]
export type ReelVideoJobInsert = Database["public"]["Tables"]["reel_video_jobs"]["Insert"]
export type StoryInsert = Database["public"]["Tables"]["stories"]["Insert"]
